server:
  port: 8081

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1?internal_logon=sysdba
    username: sys
    password: YourPassword
    driver-class-name: oracle.jdbc.OracleDriver

  security:
    user:
      name: user
      password: sawadeekrap

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect

jwt:
  secret: Z8tB93WnY6dQ2cXLm4gH7kTpJvEzUaFbY6dQ2cXLm4gH7kTY6dQ2cXLm4gH7kT
