version: '3.8'

services:
  wallet-service:
    image: walletservice-wallet-service   # or build: . if you want Compose to build it
    build: .
    ports:
      - 8082:8082
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    networks:
      - wallet-net

networks:
  wallet-net:
    external: true
